import axios from "axios";
function escapeHtml(text = "") {
  return text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&`#39`;");
}

export async function sendEmailSummary(summary) {
  try {
    const response = await axios.post(
      "https://api.resend.com/emails",
      {
        from: "WhatsApp Bot <onboarding@resend.dev>",
        to: process.env.MY_EMAIL_ADDRESS,
        subject: `📊 Daily WhatsApp Summary - ${new Date().toLocaleDateString()}`,
        html: `
          <div style="font-family: Arial, sans-serif; padding: 20px;">
            <h2>📊 Daily WhatsApp Summary</h2>

            <p>
              Here's a summary of today's WhatsApp conversations generated by Gemini.
            </p>

            <div
              style="
                background:#f7f7f7;
                padding:15px;
                border-radius:8px;
                white-space:pre-wrap;
              "
            >
              ${escapeHtml(summary)}
            </div>

            <hr />

            <p style="font-size:12px;color:#777;">
              Generated automatically by your WhatsApp AI Assistant.
            </p>
          </div>
        `,
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
          "Content-Type": "application/json",
        },
        timeout: 1000,
      },
    );
  } catch (error) {
    console.error("❌ Failed to send daily summary email:");

    if (error.response) {
      console.error(JSON.stringify(error.response.data, null, 2));
    } else {
      console.error(error.message);
    }
  }
}
