import express from "express";
import dotenv from "dotenv";
import axios from "axios";
import { GoogleGenAI } from "@google/genai";
import nodemailer from "nodemailer"; // Cleaned up to match your ES Module structure

dotenv.config();

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

// 1. Configure your email transporter
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER, // Set this in your Render env variables
    pass: process.env.EMAIL_PASS, // Use a 16-character Google App Password here
  },
});

async function sendWhatsappMessage(to, text) {
  try {
    // Ensure the phone number is just digits, no plus signs or spaces
    const cleanPhone = String(to).replace(/\D/g, "");

    // Force Gemini's text into a completely clean, flat string
    const cleanText = String(text)
      .replace(/[\r\n]+/g, " ") // Flatten line breaks into single spaces
      .replace(/"/g, '\\"') // Escape double quotes
      .trim();

    console.log(`Sending sanitized text to ${cleanPhone}: "${cleanText}"`);

    await axios.post(
      `https://graph.facebook.com/v23.0/${process.env.PHONE_NUMBER_ID}/messages`,
      {
        messaging_product: "whatsapp",
        to: cleanPhone,
        type: "text",
        text: {
          body: cleanText,
        },
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.WHATSAPP_TOKEN}`,
          "Content-Type": "application/json",
        },
      },
    );
    console.log("✓ Message successfully delivered to WhatsApp API");
  } catch (error) {
    console.error("Error sending WhatsApp message:");
    if (error.response) {
      console.error(JSON.stringify(error.response.data, null, 2));
    } else {
      console.error(error.message);
    }
  }
}

const app = express();
app.use(express.json());

// --- 1. WEBHOOK VERIFICATION (GET HANDLER) ---
app.get("/webhook", (req, res) => {
  const mode = req.query["hub.mode"];
  const token = req.query["hub.verify_token"];
  const challenge = req.query["hub.challenge"];

  const MY_VERIFY_TOKEN = "your_secret_token_here";

  console.log("=== WEBHOOK VERIFICATION ATTEMPT ===");
  console.log("Received Token:", token);

  if (mode === "subscribe" && token === MY_VERIFY_TOKEN) {
    console.log("--- VERIFICATION SUCCESSFUL! ---");
    return res.status(200).send(challenge);
  } else {
    console.log("--- VERIFICATION FAILED: Token Mismatch ---");
    return res.sendStatus(403);
  }
});

// --- 2. OPTIMIZED: MESSAGE RECEIVER (POST HANDLER) ---
app.post("/webhook", async (req, res) => {
  try {
    console.log("INCOMING WEBHOOK BODY:", JSON.stringify(req.body, null, 2));

    const entry = req.body?.entry?.[0];
    const change = entry?.changes?.[0];
    const value = change?.value;

    // Immediately ignore status updates (delivered, read receipts)
    if (value?.statuses && !value?.messages) {
      console.log("Ignored status receipt payload.");
      return res.sendStatus(200);
    }

    const message = value?.messages?.[0];
    if (!message) {
      console.log("Webhook received, but no message object found.");
      return res.sendStatus(200);
    }

    const phone = message.from;
    const userMessage = message.text?.body || message.body;

    if (!userMessage) {
      console.log("Message object found, but text body was empty.");
      return res.sendStatus(200);
    }

    const senderName = value?.contacts?.[0]?.profile?.name || "Unknown User";
    console.log(
      `★★★ PARSED SUCCESS ★★★ From: ${senderName} (${phone}) | Msg: ${userMessage}`,
    );

    // --- MEETING KEYWORD FILTER & EMAIL TRIGGER ---
    const lowerMessage = userMessage.toLowerCase();
    const keywords = [
      "meet",
      "meeting",
      "schedule",
      "appointment",
      "call",
      "discuss",
    ];
    const wantsToMeet = keywords.some((keyword) =>
      lowerMessage.includes(keyword),
    );

    if (wantsToMeet) {
      console.log(
        `🚨 Meeting intent detected from ${senderName}. Sending email alert...`,
      );

      const mailOptions = {
        from: process.env.MY_EMAIL_ADDRESS,
        to: process.env.MY_EMAIL_ADDRESS, // Sends the message directly back to your own inbox
        subject: `📅 New WhatsApp Meeting Request: ${senderName}`,
        html: `
          <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
            <h2 style="color: #25D366;">New Meeting Intent Detected!</h2>
            <p><strong>Sender Name:</strong> ${senderName}</p>
            <p><strong>WhatsApp Number:</strong> +${phone}</p>
            <p><strong>Raw Message:</strong> "${userMessage}"</p>
            <hr style="border: 0; border-top: 1px solid #eeeeee;" />
            <p style="font-size: 12px; color: #777777;"><em>This notification was auto-generated by your WhatsApp Bot backend.</em></p>
          </div>
        `,
      };

      // Fire and forget email block so it doesn't slow down the response loop
      transporter
        .sendMail(mailOptions)
        .then(() =>
          console.log(
            "📨 Email notification successfully routed to your inbox.",
          ),
        )
        .catch((err) =>
          console.error(
            "❌ Failed to transmit notification email:",
            err.message,
          ),
        );
    }

    // Acknowledge Meta immediately to prevent timeout retries
    res.sendStatus(200);

    // Pass the cleaned arguments to your background worker
    processAIResponse(phone, userMessage);
  } catch (error) {
    console.error("Critical error inside Webhook Router:", error.message);
    if (!res.headersSent) {
      res.sendStatus(200);
    }
  }
});

// Helper function to handle the long-running AI generation and messaging
async function processAIResponse(phone, userMessage) {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-3.1-flash-lite",
      contents: `
You are Dickson's WhatsApp AI assistant.
Be concise and friendly.

User: ${userMessage}
`,
    });

    const aiReply = response.text ?? "Sorry, I couldn't generate a response.";
    console.log("AI Reply:", aiReply);

    await sendWhatsappMessage(phone, aiReply);
  } catch (error) {
    console.error("AI Processing Error:", error.message);
  }
}

app.listen(3000, () => {
  console.log("Server running on port 3000");
});
